image: node:10.18.1

pipelines:
  default:
    - step:
        name: 'Prepare dependencies'
        caches:
          - node
        script:
          - yarn install
          - sh -c 'yarn audit; [[ $? -ge 4 ]] && exit 1 || exit  0'
    - parallel:
        - step:
            name: "Elements linter"
            caches:
              - node
            script:
              - cd ./packages/elements
              - yarn lint:ci
        - step:
            name: "Library linter"
            caches:
              - node
            script:
              - cd ./packages/library
              - yarn lint:ci
        - step:
            name: "Playground linter"
            caches:
              - node
            script:
              - cd ./packages/playground
              - yarn lint:ci
        - step:
            name: "Common linter"
            caches:
              - node
            script:
              - cd ./packages/common
              - yarn lint:ci
    - parallel:
        - step:
            name: "Elements tests"
            caches:
              - node
            script:
              - cd ./packages/elements
              - yarn test
        - step:
            name: "Library tests"
            caches:
              - node
            script:
              - cd ./packages/library
              - yarn test
        - step:
            name: "Playground tests"
            caches:
              - node
            script:
              - cd ./packages/playground
              - yarn test
        - step:
            name: "Common tests"
            caches:
              - node
            script:
              - cd ./packages/common
              - yarn test
